apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: store-pjt
  namespace: store-pjt
  labels:
    app: store-pjt
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
    - "store-pjt.c56380c.kyma.ondemand.com"
  service:
    name: approuter
    port: 5000
  rules:
    - path: /*
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]
      noAuth: true