apiVersion: v1
kind: ConfigMap
metadata:
  name: approuter-xs-app
  namespace: store-pjt
data:
  xs-app.json: |
    {
      "welcomeFile": "/index.html",
      "authenticationMethod": "route",
      "routes": [
        {
          "source": "^/inventory/(.*)$",
          "target": "/inventory/$1",
          "destination": "cap-backend",
          "authenticationType": "xsuaa",
          "csrfProtection": false
        },
        {
          "source": "^(.*)$",
          "target": "$1",
          "destination": "cap-backend",
          "authenticationType": "xsuaa"
        }
      ]
    }